parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2022
  project: ./tsconfig.json

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:sonarjs/recommended-legacy
  - plugin:import/typescript

plugins:
  - simple-import-sort
  - import
  - only-error
  - unused-imports
  - sonarjs

settings:
  import/resolver:

rules:
  import/exports-last: error
  import/first: error
  import/no-duplicates: error
  import/order: off

  simple-import-sort/imports: error
  simple-import-sort/exports: error

  unused-imports/no-unused-imports: error

  import/no-extraneous-dependencies:
    - error
    - devDependencies: false

overrides:
  - files:
      - '*.spec.ts'
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
