name: Pull Requests

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.*ignore'
      - '**.env*'
      - renovate.json
      - docker-compose.yaml
      - '**deployment.yaml'

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-code-quality:
    name: Format and lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format project
        run: pnpm format

      - name: Type-check project
        run: pnpm typecheck

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
