name: Check integration

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.*ignore'
      - '**.env*'
      - renovate.json
      - docker-compose.yaml
      - '**deployment.yaml'

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-22.04
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  integration:
    name: Continuous integration checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check code formatting
        run: pnpm check:format

      - name: Check code typing
        run: pnpm check:types

      - name: Check code linting
        run: pnpm check:lint

      - name: Test project
        run: pnpm test

      - name: Build Docker image for project
        uses: docker/build-push-action@v5
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
