on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.*ignore'
      - '**.env*'
      - renovate.json
      - docker-compose.yaml
      - '**deployment.yaml'

jobs:
  integration:
    name: Continuous integration
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type-check project
        run: pnpm typecheck

      - name: Lint project
        run: pnpm lint

      - name: Test project
        run: pnpm test

      - name: Build project
        run: pnpm build

      - name: Build Docker image for project
        uses: docker/build-push-action@v4
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
